### ISSUE TITLE
Popup Window Placement and PDF files

### ISSUE THREAD

**Issue by aleckscastro** [Lusito/dict.cc-translation#19] opened 2016-07-22 12:20 UTC
In version 3.x, the Popup Window (all details) can be placed anywhere on the screen and upon new lookups, it stays in the same place. In version 4.x, however, the Popup Window (all details) seems to always move back to the center of the window where a lookup is requested.

~~Also, version 4.x doesn't seem to work within PDF files like 3.x does.~~

Using Dict.cc Translation on Ubuntu.

**Comment by Lusito** [comment] 2016-08-22 12:56
I can't reproduce the pdf problem.. maybe you are not using the firefox pdf viewer, but a plugin from a different pdf viewer?
Also, please don't write two different problems in one ticket. Create one for each.

**Comment by aleckscastro** [comment] 2016-08-22 13:18
Can you however reproduce the main problem reported in this thread - window placement? The PDF problem was merely an addendum because, like I wrote, it _seemed_ not to work within PDF files a few Firefox versions ago and no longer affects me.

**Comment by Lusito** [comment] 2016-08-22 13:24
Yes, I can. Not sure when I get the time to work on it tho. I'm currently busy with my bachelor thesis.

**Comment by Lusito** [comment] 2017-02-09 03:50
Fixed in next version.

**Closed by Lusito** 2017-02-09 03:50 UTC
Labels: bug
