### ISSUE TITLE
I am using a regular pc mouse, this happens on every page and I am using the Firefox version 59.0.2.

### ISSUE THREAD

**Issue by kh00** [Lusito/dict.cc-translation#45] opened 2019-07-26 08:16 UTC
I am using a regular pc mouse, this happens on every page and I am using the Firefox version 59.0.2.

_Originally posted by @CennoxX in https://github.com/Lusito/dict.cc-translation/issues/34#issuecomment-378564119_

**Comment by Lusito** [comment] 2019-08-04 11:27
I can't reproduce this issue, since I don't own a mac. I've tried analyzing possible issues in the code, but didn't get anywhere.
If you want to help debug it, please try this (on a mac):

- disable the add-on
- visit http://lusito.info/rocker-test.html
- on the gray area, try doing a rocker gesture from right to left mouse button
- on the gray area, try doing a rocker gesture from left to right mouse button
- copy the text of the log textarea and paste it here. With that info, I can inspect what is happening on a mac and maybe fix it.

**Comment by Lusito** [comment] 2019-09-11 20:08
Closing this, as kh00 is some sort of bot.

**Closed by Lusito** 2019-09-11 20:08 UTC
