### ISSUE TITLE
Cyrillic / Unicode Language not recognized

### ISSUE THREAD

**Issue by scrapix** [Lusito/dict.cc-translation#23] opened 2016-10-29 23:04 UTC
If I try to translate Cyrillic words, they are not recognized. Instead of "выиграла" the add-on tries to translate "Ð²ÑÐ¸Ð³ÑÐ°Ð»Ð" which obviously doesn't get any result. I'd be very happy and thankful if you could solve this issue. Thank you for your work - this add-on is really nice!

**Comment by Lusito** [comment] 2016-11-01 12:44
Could you please specify the language and the website you tested it on? And also the translation method you used (quick, popup, ...).
Because here on github, I can't reproduce it. In the context Menu and on the dict.cc page it shows the original word correctly. (since I don't know the language, I can't say if it translates correctly)

**Comment by scrapix** [comment] 2016-12-14 19:10
For example on: https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D1%8F 

![screenshot_dict_plugin](https://cloud.githubusercontent.com/assets/23144020/21196815/639ab6d0-c239-11e6-8a2c-b58cd045feef.jpg)

**Comment by Lusito** [comment] 2016-12-14 20:56
Thanks for the info. Some observations here:
This unicode problem seems to occur only with the pocket translation window.
On dict.cc itself and even the dcc-gadget (which is used for the quick translation), it works just fine.
Also, the word you selected it not translated on dict.cc, which is why you don't get quick translation results (the "typo?" message).

You can see the difference when you try the word она (left to the word you selected), which translates fine in quick translation, but has messed up unicode in pocket translation.

This issue however is an issue on the pocket.dict.cc part, which I have no control over.
I will notify the author of dict.cc about this issue tho.

**Comment by Lusito** [comment] 2016-12-15 21:20
Paul fixed the issue, so I'll close this issue. Please re-open if you still have issues.

**Closed by Lusito** 2016-12-15 21:20 UTC
Labels: help wanted
